#!/bin/bash
# LGSM fn_check_error function
# Author: Daniel Gibbs
# Website: http://gameservermanagers.com
# Version: 011115

selfname="$(basename $0)"

error_check(){
    "$@"
    local status=$?
    if [ $status -ne 0 ]; then
        echo "${selfname}: error with ${1}" >&2
    	exit $status
    fi
}